package com.gridgain.titanic.config;

import com.mchange.v2.c3p0.ComboPooledDataSource;
import java.io.InputStream;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Properties;
import javax.cache.configuration.Factory;
import javax.sql.DataSource;
import org.apache.ignite.cache.CacheAtomicityMode;
import org.apache.ignite.cache.CacheMode;
import org.apache.ignite.cache.QueryEntity;
import org.apache.ignite.cache.store.jdbc.CacheJdbcPojoStoreFactory;
import org.apache.ignite.cache.store.jdbc.JdbcType;
import org.apache.ignite.cache.store.jdbc.JdbcTypeField;
import org.apache.ignite.cache.store.jdbc.dialect.BasicJdbcDialect;
import org.apache.ignite.configuration.CacheConfiguration;
import org.apache.ignite.configuration.IgniteConfiguration;
import org.apache.ignite.spi.discovery.tcp.TcpDiscoverySpi;
import org.apache.ignite.spi.discovery.tcp.ipfinder.vm.TcpDiscoveryVmIpFinder;

/** This file was generated by Ignite Web Console (03/23/2020, 18:23) **/
public class ClientConfigurationFactory {
    /** Secret properties loading. **/
    private static final Properties props = new Properties();

    static {
        try (InputStream in = IgniteConfiguration.class.getClassLoader().getResourceAsStream("secret.properties")) {
            props.load(in);
        }
        catch (Exception ignored) {
            // No-op.
        }
    }

    /** Helper class for datasource creation. **/
    public static class DataSources {
        public static final ComboPooledDataSource INSTANCE_dsGeneric_titanic = createdsGeneric_titanic();

        private static ComboPooledDataSource createdsGeneric_titanic() {
            ComboPooledDataSource dsGeneric_titanic = new ComboPooledDataSource();

            dsGeneric_titanic.setJdbcUrl(props.getProperty("dsGeneric_titanic.jdbc.url"));
            dsGeneric_titanic.setUser(props.getProperty("dsGeneric_titanic.jdbc.username"));
            dsGeneric_titanic.setPassword(props.getProperty("dsGeneric_titanic.jdbc.password"));

            return dsGeneric_titanic;
        }
    }

    /**
     * Configure grid.
     * 
     * @return Ignite configuration.
     * @throws Exception If failed to construct Ignite configuration instance.
     **/
    public static IgniteConfiguration createConfiguration() throws Exception {
        IgniteConfiguration cfg = new IgniteConfiguration();

        cfg.setClientMode(true);
        cfg.setIgniteInstanceName("Titanic");

        TcpDiscoverySpi discovery = new TcpDiscoverySpi();

        TcpDiscoveryVmIpFinder ipFinder = new TcpDiscoveryVmIpFinder();

        ipFinder.setAddresses(Arrays.asList("127.0.0.1:38500..38510"));

        discovery.setIpFinder(ipFinder);

        cfg.setDiscoverySpi(discovery);

        cfg.setCacheConfiguration(cacheTitanicCache());

        return cfg;
    }

    /**
     * Create configuration for cache "TitanicCache".
     * 
     * @return Configured cache.
     * @throws Exception if failed to create cache configuration.
     **/
    public static CacheConfiguration cacheTitanicCache() throws Exception {
        CacheConfiguration ccfg = new CacheConfiguration();

        ccfg.setName("TitanicCache");
        ccfg.setCacheMode(CacheMode.PARTITIONED);
        ccfg.setAtomicityMode(CacheAtomicityMode.ATOMIC);
        ccfg.setCopyOnRead(true);
        ccfg.setSqlSchema("TITANIC");

        CacheJdbcPojoStoreFactory cacheStoreFactory = new CacheJdbcPojoStoreFactory();

        cacheStoreFactory.setDataSourceFactory(new Factory<DataSource>() {
            /** {@inheritDoc} **/
            @Override public DataSource create() {
                return DataSources.INSTANCE_dsGeneric_titanic;
            };
        });

        cacheStoreFactory.setDialect(new BasicJdbcDialect());

        cacheStoreFactory.setTypes(jdbcTypeTitanic(ccfg.getName()));

        ccfg.setCacheStoreFactory(cacheStoreFactory);

        ccfg.setReadThrough(true);
        ccfg.setEagerTtl(true);

        ArrayList<QueryEntity> qryEntities = new ArrayList<>();

        QueryEntity qryEntity = new QueryEntity();

        qryEntity.setKeyType("com.gridgain.titanic.model.TitanicKey");
        qryEntity.setValueType("com.gridgain.titanic.model.Titanic");
        qryEntity.setTableName("Titanic");

        HashSet<String> keyFields = new HashSet<>();

        keyFields.add("passengerid");

        qryEntity.setKeyFields(keyFields);

        LinkedHashMap<String, String> fields = new LinkedHashMap<>();

        fields.put("passengerid", "java.lang.Integer");
        fields.put("survived", "java.lang.Integer");
        fields.put("pclass", "java.lang.Integer");
        fields.put("name", "java.lang.String");
        fields.put("sex", "java.lang.String");
        fields.put("age", "java.lang.Integer");
        fields.put("sibsp", "java.lang.Integer");
        fields.put("parch", "java.lang.Integer");
        fields.put("ticket", "java.lang.String");
        fields.put("fare", "java.lang.Double");
        fields.put("cabin", "java.lang.String");
        fields.put("embarked", "java.lang.String");

        qryEntity.setFields(fields);

        HashSet<String> notNullFields = new HashSet<>();

        notNullFields.add("passengerid");

        qryEntity.setNotNullFields(notNullFields);
        qryEntities.add(qryEntity);

        ccfg.setQueryEntities(qryEntities);

        return ccfg;
    }

    /**
     * Create JDBC type for "jdbcTypeTitanic".
     * 
     * @param cacheName Cache name.
     * @return Configured JDBC type.
     **/
    private static JdbcType jdbcTypeTitanic(String cacheName) {
        JdbcType type = new JdbcType();

        type.setCacheName(cacheName);
        type.setKeyType("com.gridgain.titanic.model.TitanicKey");
        type.setValueType("com.gridgain.titanic.model.Titanic");
        type.setDatabaseSchema("TITANIC");
        type.setDatabaseTable("titanic");

        type.setKeyFields(new JdbcTypeField(Types.VARCHAR, "PassengerId", String.class, "passengerid"));

        type.setValueFields(
            new JdbcTypeField(Types.VARCHAR, "PassengerId", String.class, "passengerid"),
            new JdbcTypeField(Types.VARCHAR, "Survived", String.class, "survived"),
            new JdbcTypeField(Types.VARCHAR, "Pclass", String.class, "pclass"),
            new JdbcTypeField(Types.VARCHAR, "Name", String.class, "name"),
            new JdbcTypeField(Types.VARCHAR, "Sex", String.class, "sex"),
            new JdbcTypeField(Types.VARCHAR, "Age", String.class, "age"),
            new JdbcTypeField(Types.VARCHAR, "SibSp", String.class, "sibsp"),
            new JdbcTypeField(Types.VARCHAR, "Parch", String.class, "parch"),
            new JdbcTypeField(Types.VARCHAR, "Ticket", String.class, "ticket"),
            new JdbcTypeField(Types.VARCHAR, "Fare", String.class, "fare"),
            new JdbcTypeField(Types.VARCHAR, "Cabin", String.class, "cabin"),
            new JdbcTypeField(Types.VARCHAR, "Embarked", String.class, "embarked")
        );

        return type;
    }
}