package com.gridgain.titanic.model;

import java.io.Serializable;

/**
 * TitanicKey definition.
 * 
 * This file was generated by Ignite Web Console (03/23/2020, 18:23)
 **/
public class TitanicKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for passengerid. */
    private Integer passengerid;

    /** Empty constructor. **/
    public TitanicKey() {
        // No-op.
    }

    /** Full constructor. **/
    public TitanicKey(Integer passengerid) {
        this.passengerid = passengerid;
    }

    /**
     * Gets passengerid
     * 
     * @return Value for passengerid.
     **/
    public Integer getPassengerid() {
        return passengerid;
    }

    /**
     * Sets passengerid
     * 
     * @param passengerid New value for passengerid.
     **/
    public void setPassengerid(Integer passengerid) {
        this.passengerid = passengerid;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof TitanicKey))
            return false;
        
        TitanicKey that = (TitanicKey)o;

        if (passengerid != null ? !passengerid.equals(that.passengerid) : that.passengerid != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = passengerid != null ? passengerid.hashCode() : 0;

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "TitanicKey [" + 
            "passengerid=" + passengerid +
        "]";
    }
}